
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue May 16 01:37:47 CEST 2017
//----------------------------------------------------

package syntactical;

/** CUP generated class containing symbol constants. */
public class SESASym {
  /* terminals */
  public static final int FBLOQUE = 19;
  public static final int SEP = 21;
  public static final int CONS = 3;
  public static final int APACCESO = 35;
  public static final int FININSTR = 25;
  public static final int POR = 6;
  public static final int PCI = 23;
  public static final int ENTONCES = 29;
  public static final int CIACCESO = 36;
  public static final int CICON = 28;
  public static final int NUMENT = 2;
  public static final int IGUAL = 8;
  public static final int SINO = 30;
  public static final int MIENTRAS = 31;
  public static final int SBUCLE = 32;
  public static final int DIV = 7;
  public static final int DIS = 12;
  public static final int IF = 26;
  public static final int IDV = 20;
  public static final int DIM = 37;
  public static final int EOF = 0;
  public static final int ASIG = 24;
  public static final int TRUE = 16;
  public static final int error = 1;
  public static final int GCONTROL = 33;
  public static final int MENOS = 5;
  public static final int MENOR = 10;
  public static final int CON = 11;
  public static final int MAYOR = 9;
  public static final int ENT = 15;
  public static final int LOG = 14;
  public static final int PAP = 22;
  public static final int APCON = 27;
  public static final int NEG = 13;
  public static final int ACCESO = 34;
  public static final int BLOQUE = 18;
  public static final int FALSE = 17;
  public static final int PYC = 38;
  public static final int MAS = 4;
}

