
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Jul 20 19:06:32 CEST 2017
//----------------------------------------------------

package syntactical;

/** CUP generated class containing symbol constants. */
public class SESASym {
  /* terminals */
  public static final int FBLOQUE = 4;
  public static final int SEP = 5;
  public static final int CONS = 2;
  public static final int FSI = 17;
  public static final int FININSTR = 9;
  public static final int APACCESO = 19;
  public static final int POR = 26;
  public static final int PCI = 7;
  public static final int FMIENTRAS = 18;
  public static final int ENTONCES = 13;
  public static final int CIACCESO = 20;
  public static final int CICON = 12;
  public static final int NUMENT = 37;
  public static final int IGUAL = 28;
  public static final int SINO = 14;
  public static final int MIENTRAS = 15;
  public static final int SBUCLE = 16;
  public static final int DIV = 27;
  public static final int DIS = 32;
  public static final int IF = 10;
  public static final int IDV = 35;
  public static final int DIM = 36;
  public static final int EOF = 0;
  public static final int ASIG = 8;
  public static final int TRUE = 38;
  public static final int error = 1;
  public static final int MENOS = 25;
  public static final int MENOR = 30;
  public static final int CON = 31;
  public static final int MAYOR = 29;
  public static final int ENT = 23;
  public static final int LOG = 22;
  public static final int PAP = 6;
  public static final int APCON = 11;
  public static final int NEG = 33;
  public static final int ACCESO = 34;
  public static final int BLOQUE = 3;
  public static final int FALSE = 39;
  public static final int PYC = 21;
  public static final int MAS = 24;
}

